import React, { useEffect, useState } from 'react';
import Head from 'next/head'
const axios = require('axios');
import Link from 'next/link'
import localUrl from '../../utility/localUrl';
import Image from 'next/image';
import style from './blog.module.css'
import {useRouter} from "next/router";
import Header from '../../components/layouts/header/header';
import Footer from '../../components/layouts/footer/footer';
const Post = () => {

    const { query } = useRouter();
    
    const [Post, setRelatedPost] = useState([]);

    //  post data call
    useEffect(()=>{
     axios.get(localUrl()+'/json/singleblog.json')
     .then(response => {
         const post = response.data ; 
         setRelatedPost(post);
 
     })
     .catch(err => console.error(err))
     .then(() => {console.log("final done post")})
   },[])

   
    return (
        <>
        <Head>
        <title>Single blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header/>


        <div className='my-16 blog__single__section__padding'>
              
              <p className='pt-10 text-lg'>Jan 27 2022</p>

               <p className={`${style.blog__title} mt-12 text-4xl font-bold`}>43% say they kept their New Year’s resolution last year: Public ki Awaaz poll</p>
               <p className={style.blog__description} dangerouslySetInnerHTML={{__html: Post}}/>

               <div className='mt-8'>
                 <p className='text-md font-medium'>Published by</p>
                 <p className='mt-1 text-lg font-semibold'>Team TextFm</p>
               </div>
            </div>
            <Footer/>
        </>
       
    );
};

export default Post;