import React, { useEffect, useState } from 'react';
import Head from 'next/head'
const axios = require('axios');
import Link from 'next/link'
import localUrl from '../../utility/localUrl';
import Image from 'next/image';
import style from './blog.module.css'
import {useRouter} from "next/router";
import Header from '../../components/layouts/header/header';
import Footer from '../../components/layouts/footer/footer';

const Post = () => {

    const { query } = useRouter();
    
    const [Post, setRelatedPost] = useState([]);

    //  post data call
    useEffect(()=>{
     axios.get(localUrl()+'/json/blog.json')
     .then(response => {
         const post = response.data ; 
         setRelatedPost(post);
 
     })
     .catch(err => console.error(err))
     .then(() => {console.log("final done post")})
   },[])

   
    return (
        <>
        <Head>
        <title>Single blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header/>


        <div className='my-16 blog__single__section__padding'>
                <div className='lg:flex flex-wrap md:flex gap-10'>
                    
                    <div className='lg:w-8/12 box__shadow rounded-2xl lg:px-10 md:px-10 px-5 py-8 '>
                        <Image src="/images/gig4.jpg" className={`${style.post__image} rounded-3xl `} width="1200px" height="700px" alt='img'  />

                        <h1 className='lg:my-8 md:my-8 my-4 lg:text-2xl md:text-2xl text-lg font-medium'>Horoscope For Today February 20, 2022</h1>

                        <div className='mt-2 w-full block '>
                           <audio src="" controls/>
                        </div>


                        {/* <div className='my-5 text-3xl flex justify-between '> 
                                        
                            <div className='flex gap-10'>
                            <i className="cursor-pointer las la-thumbs-up"></i>
                            <a href='#commentbox' className="cursor-pointer las la-comment"></a>
                            <i className="orange-icon cursor-pointer las la-heart"></i>
                            <i className="cursor-pointer las lar la-id-badge"></i>
                            </div>


                        </div> */}

                        <p className={`${style.blog__description} mt-6`}> Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, </p>
                    </div>
                    
                    <div className='lg:w-3/12 lg:mt-0 md:mt-0 mt-8'>
                        <p className='text-3xl font-medium'> Related Articles</p>

                        <div className="blogs py-8 grid grid-cols-1 gap-6">
                     {
                        Post.map((item, index) =>{
                            return(
                            <div key={index} className="blog_item">
                                <Image width="800px" src="/images/gig4.jpg"   height="530px" alt={item.post_title}  />
                            
                              <div className='px-5 pt-4 pb-2 '>
                                <Link
                                        href={{
                                        pathname: '/blog/[slug]',
                                        query: { slug: item.slug },
                                    }}
                                    >
                                    <a className="text-2xl font-medium ">{item.post_title}</a>
                                    </Link>

                                    <p className='post__date my-3'> February 23, 22 </p>
                              </div>
                                

                            </div>
                            )
                        })
                    }
            
            </div>
                           
                    </div>

                </div>

                
            </div>

            <Footer/>
        </>
       
    );
};

export default Post;