import axios from 'axios';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import React, { useEffect, useState } from 'react';
import Footer from '../../components/layouts/footer/footer';
import Header from '../../components/layouts/header/header';
import postTitleTrim from '../../utility/postTitleTrim';
// import Image from 'next/image';
export default function Index() {
 
    const [Post, setPost] = useState([]);

   //  post data call
   useEffect(()=>{
    axios.get('./json/blog.json')
    .then(response => {
        const post = response.data ; 
        setPost(post);

    })
    .catch(err => console.error(err))
    .then(() => {console.log("final done post")})
  },[])


  return (
  <div>
     <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
     
          {/* post section */}
          <Header/>

          <div className="pt-4 pb-16 bg-gray-50  lg:px-40 md:px-16 px-6">
                  <div className="blogs py-8 grid lg:grid-cols-3 md:grid-cols-2 grid-cols-1 gap-6">
                          {
                              Post.map((item, index) =>{
                                  return(
                                  <div key={index} className="mt-6 bg-white rounded-lg shadow-lg px-5 py-4 box__shadow border-t-4 border-b-4 blue-border">
                                      <div className='mt-2 '>

                                          <div className='flex justify-between '>
                                            <div>
                                              <Link
                                                    href={{
                                                    pathname: '/blog/[slug]',
                                                    query: { slug: item.slug },
                                                }}
                                                >
                                                  
                                                <a> <Image width="500px" height="300px" src="/images/gig4.jpg" className='rounded'  alt={item.post_title}  />
                                                </a>

                                              </Link>
                                              </div>
                                          </div>

                                            <div>
                                              <div className='mt-3'>

                                               {/* <p className='md:mt-0 lg:mt-0 mt-2' >Publish Date : 11.04.2022</p> */}
                                             
                                              <Link
                                                    href={{
                                                    pathname: '/blog/[slug]',
                                                    query: { slug: item.slug },
                                                }}
                                                >
                                                <a className="lg:text-lg md:text-lg font-medium ">{postTitleTrim(item.post_title)}</a>

                                              </Link>

                                              </div>

                                              <div className='mt-2'>
                                                <audio src="" controls/>
                                              </div>

                                              <div>
                                                <p className='mt-4' >{item.des}</p>
                                                  <button className='mt-3 w-full bg-blue py-3 shadow-lg border block rounded'>POST SOURCE</button>
                                              </div>

                                            </div>
                                      </div>
                                  </div>
                                  )
                              })
                          }
                  
                  </div>
              </div>
    </div>
   
   <Footer/>
    
  </div>

  )
}
